### ISSUE TITLE
Think this line is missing </div> but i'll leave to see where you want this div to end

### ISSUE THREAD

**Issue by mikewclee** [microxgleek94/ColumbiaProject_-1#29]
https://github.com/microxgleek94/ColumbiaProject_-1/blob/7e0e768879375dac3c9ae585182f4924de48dc76/index.html#L56

**Comment by nexus-codingg** [comment]
gotcha! thanks i'll add it in

**Comment by mikewclee** [comment]
Kikki fixed it
